//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.14 at 01:52:08 PM MESZ 
//


package org.osmtools.osc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bounds complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bounds">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="minlat" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="minlon" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="maxlat" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="maxlon" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="origin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bounds")
public class Bounds {

    @XmlAttribute(name = "minlat", required = true)
    protected float minlat;
    @XmlAttribute(name = "minlon", required = true)
    protected float minlon;
    @XmlAttribute(name = "maxlat", required = true)
    protected float maxlat;
    @XmlAttribute(name = "maxlon", required = true)
    protected float maxlon;
    @XmlAttribute(name = "origin")
    protected String origin;

    /**
     * Gets the value of the minlat property.
     * 
     */
    public float getMinlat() {
        return minlat;
    }

    /**
     * Sets the value of the minlat property.
     * 
     */
    public void setMinlat(float value) {
        this.minlat = value;
    }

    /**
     * Gets the value of the minlon property.
     * 
     */
    public float getMinlon() {
        return minlon;
    }

    /**
     * Sets the value of the minlon property.
     * 
     */
    public void setMinlon(float value) {
        this.minlon = value;
    }

    /**
     * Gets the value of the maxlat property.
     * 
     */
    public float getMaxlat() {
        return maxlat;
    }

    /**
     * Sets the value of the maxlat property.
     * 
     */
    public void setMaxlat(float value) {
        this.maxlat = value;
    }

    /**
     * Gets the value of the maxlon property.
     * 
     */
    public float getMaxlon() {
        return maxlon;
    }

    /**
     * Sets the value of the maxlon property.
     * 
     */
    public void setMaxlon(float value) {
        this.maxlon = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigin(String value) {
        this.origin = value;
    }

}
