//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.14 at 01:48:39 PM MESZ 
//


package org.osm.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Osm_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Osm_type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="node"/>
 *     &lt;enumeration value="way"/>
 *     &lt;enumeration value="relation"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Osm_type")
@XmlEnum
public enum OsmType {

    @XmlEnumValue("node")
    NODE("node"),
    @XmlEnumValue("way")
    WAY("way"),
    @XmlEnumValue("relation")
    RELATION("relation");
    private final String value;

    OsmType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OsmType fromValue(String v) {
        for (OsmType c: OsmType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
